INSERT INTO public.activities (description,"date",duration_in_days,winner) VALUES
	 ('Первый в России JAVABOOTCAMP ','2022-10-25 00:00:00',3,NULL),
	 ('Встреча клуба Leader Stories «Зачем развивать сотрудников? Они же уйдут» ','2023-04-18 00:00:00',3,NULL),
	 ('Поисковая оптимизация. SEO оптимизация ','2022-08-15 00:00:00',2,NULL),
	 ('Поликом Про и InfoWatch: круглый стол по информационной безопасности в Санкт-Петербурге ','2022-02-02 00:00:00',2,NULL),
	 ('Получи «100500» лидов в первые 5 секунд ','2023-09-02 00:00:00',3,NULL),
	 ('Постоянно доступен: Налаживаем омниканальную коммуникацию с клиентами ','2023-10-29 00:00:00',3,NULL),
	 ('Построение гиперконвергентной инфраструктуры и VDI-решения ','2023-10-28 00:00:00',3,NULL),
	 ('Практикум по Customer Development с экспертом ФРИИ: грамотные продажи за 4 часа ','2022-06-03 00:00:00',3,NULL),
	 ('Практическое применение диаграммы потоков данных (DFD, Data Flow Diagram) ','2023-11-27 00:00:00',3,NULL),
	 ('Практическое применение диаграммы состояний (UML StateChart) ','2022-06-17 00:00:00',3,NULL);
INSERT INTO public.activities (description,"date",duration_in_days,winner) VALUES
	 ('Первая встреча клуба «Leader stories» ','2022-03-15 00:00:00',1,1),
	 ('Первый IoT-Forum в Санкт-Петербурге ','2023-05-30 00:00:00',3,3),
	 ('План проекта: практические советы, типичные ошибки ','2023-07-11 00:00:00',2,5),
	 ('Планирование проекта: что делать после того, как выяснили цель ','2022-03-20 00:00:00',1,7),
	 ('Поисковая оптимизация (SEO) ','2022-08-10 00:00:00',1,8),
	 ('Пользовательские требования ','2023-08-08 00:00:00',2,10),
	 ('Практикум «Обогнать конкурентов: усиливаем продажи и создаем клиентский сервис» ','2022-07-28 00:00:00',2,9),
	 ('Практический воркшоп по созданию договоренностей в Scrum-команде ','2022-05-16 00:00:00',1,13),
	 ('Презентационная сессия «TTD: технологии для жизни 2022» ','2022-01-30 00:00:00',2,15),
	 ('Презентация курса «Методы, технологии, инструменты обучения персонала в технических, продуктовых и IT-компаниях» ','2023-10-01 00:00:00',3,17);
INSERT INTO public.activitiy_types ("name") VALUES
	 ('IT в бизнесе'),
	 ('Разработка приложений'),
	 ('IT-инфраструктура'),
	 ('Стартапы'),
	 ('Информационная безопасность');
INSERT INTO public.cities ("name") VALUES
	 ('Абаза'),
	 ('Абакан'),
	 ('Абдулино'),
	 ('Абинск'),
	 ('Агидель'),
	 ('Агрыз'),
	 ('Адыгейск'),
	 ('Азнакаево'),
	 ('Азов'),
	 ('Ак-Довурак');
INSERT INTO public.cities ("name") VALUES
	 ('Аксай'),
	 ('Алагир'),
	 ('Алапаевск'),
	 ('Алатырь'),
	 ('Алдан'),
	 ('Алейск'),
	 ('Александров'),
	 ('Александровск'),
	 ('Александровск-Сахалинский'),
	 ('Алексеевка');
INSERT INTO public.cities ("name") VALUES
	 ('Алексин'),
	 ('Алзамай'),
	 ('Алупкане призн.'),
	 ('Алуштане призн.'),
	 ('Альметьевск'),
	 ('Амурск'),
	 ('Анадырь'),
	 ('Анапа'),
	 ('Ангарск'),
	 ('Андреаполь');
INSERT INTO public.cities ("name") VALUES
	 ('Анжеро-Судженск'),
	 ('Анива'),
	 ('Апатиты'),
	 ('Апрелевка'),
	 ('Апшеронск'),
	 ('Арамиль'),
	 ('Аргун'),
	 ('Ардатов'),
	 ('Ардон'),
	 ('Арзамас');
INSERT INTO public.cities ("name") VALUES
	 ('Аркадак'),
	 ('Армавир'),
	 ('Армянскне призн.'),
	 ('Арсеньев'),
	 ('Арск'),
	 ('Артём'),
	 ('Артёмовск'),
	 ('Артёмовский'),
	 ('Архангельск'),
	 ('Асбест');
INSERT INTO public.cities ("name") VALUES
	 ('Асино'),
	 ('Астрахань'),
	 ('Аткарск'),
	 ('Ахтубинск'),
	 ('Ачинск'),
	 ('Аша'),
	 ('Бабаево'),
	 ('Бабушкин'),
	 ('Бавлы'),
	 ('Багратионовск');
INSERT INTO public.cities ("name") VALUES
	 ('Байкальск'),
	 ('Баймак'),
	 ('Бакал'),
	 ('Баксан'),
	 ('Балабаново'),
	 ('Балаково'),
	 ('Балахна'),
	 ('Балашиха'),
	 ('Балашов'),
	 ('Балей');
INSERT INTO public.cities ("name") VALUES
	 ('Балтийск'),
	 ('Барабинск'),
	 ('Барнаул'),
	 ('Барыш'),
	 ('Батайск'),
	 ('Бахчисарайне призн.'),
	 ('Бежецк'),
	 ('Белая Калитва'),
	 ('Белая Холуница'),
	 ('Белгород');
INSERT INTO public.cities ("name") VALUES
	 ('Белебей'),
	 ('Белёв'),
	 ('Белинский'),
	 ('Белово'),
	 ('Белогорск'),
	 ('Белогорскне призн.'),
	 ('Белозерск'),
	 ('Белокуриха'),
	 ('Беломорск'),
	 ('Белоозёрский');
INSERT INTO public.cities ("name") VALUES
	 ('Белорецк'),
	 ('Белореченск'),
	 ('Белоусово'),
	 ('Белоярский'),
	 ('Белый'),
	 ('Бердск'),
	 ('Березники'),
	 ('Берёзовский'),
	 ('Беслан'),
	 ('Бийск');
INSERT INTO public.cities ("name") VALUES
	 ('Бикин'),
	 ('Билибино'),
	 ('Биробиджан'),
	 ('Бирск'),
	 ('Бирюсинск'),
	 ('Бирюч'),
	 ('Благовещенск'),
	 ('Благодарный'),
	 ('Бобров'),
	 ('Богданович');
INSERT INTO public.cities ("name") VALUES
	 ('Богородицк'),
	 ('Богородск'),
	 ('Боготол'),
	 ('Богучар'),
	 ('Бодайбо'),
	 ('Бокситогорск'),
	 ('Болгар'),
	 ('Бологое'),
	 ('Болотное'),
	 ('Болохово');
INSERT INTO public.cities ("name") VALUES
	 ('Болхов'),
	 ('Большой Камень'),
	 ('Бор'),
	 ('Борзя'),
	 ('Борисоглебск'),
	 ('Боровичи'),
	 ('Боровск'),
	 ('Бородино'),
	 ('Братск'),
	 ('Бронницы');
INSERT INTO public.cities ("name") VALUES
	 ('Брянск'),
	 ('Бугульма'),
	 ('Бугуруслан'),
	 ('Будённовск'),
	 ('Бузулук'),
	 ('Буинск'),
	 ('Буй'),
	 ('Буйнакск'),
	 ('Бутурлиновка'),
	 ('Валдай');
INSERT INTO public.cities ("name") VALUES
	 ('Валуйки'),
	 ('Велиж'),
	 ('Великие Луки'),
	 ('Великий Новгород'),
	 ('Великий Устюг'),
	 ('Вельск'),
	 ('Венёв'),
	 ('Верещагино'),
	 ('Верея'),
	 ('Верхнеуральск');
INSERT INTO public.cities ("name") VALUES
	 ('Верхний Тагил'),
	 ('Верхний Уфалей'),
	 ('Верхняя Пышма'),
	 ('Верхняя Салда'),
	 ('Верхняя Тура'),
	 ('Верхотурье'),
	 ('Верхоянск'),
	 ('Весьегонск'),
	 ('Ветлуга'),
	 ('Видное');
INSERT INTO public.cities ("name") VALUES
	 ('Вилюйск'),
	 ('Вилючинск'),
	 ('Вихоревка'),
	 ('Вичуга'),
	 ('Владивосток'),
	 ('Владикавказ'),
	 ('Владимир'),
	 ('Волгоград'),
	 ('Волгодонск'),
	 ('Волгореченск');
INSERT INTO public.cities ("name") VALUES
	 ('Волжск'),
	 ('Волжский'),
	 ('Вологда'),
	 ('Володарск'),
	 ('Волоколамск'),
	 ('Волосово'),
	 ('Волхов'),
	 ('Волчанск'),
	 ('Вольск'),
	 ('Воркута');
INSERT INTO public.cities ("name") VALUES
	 ('Воронеж'),
	 ('Ворсма'),
	 ('Воскресенск'),
	 ('Воткинск'),
	 ('Всеволожск'),
	 ('Вуктыл'),
	 ('Выборг'),
	 ('Выкса'),
	 ('Высоковск'),
	 ('Высоцк');
INSERT INTO public.cities ("name") VALUES
	 ('Вытегра'),
	 ('Вышний Волочёк'),
	 ('Вяземский'),
	 ('Вязники'),
	 ('Вязьма'),
	 ('Вятские Поляны'),
	 ('Гаврилов Посад'),
	 ('Гаврилов-Ям'),
	 ('Гагарин'),
	 ('Гаджиево');
INSERT INTO public.cities ("name") VALUES
	 ('Гай'),
	 ('Галич'),
	 ('Гатчина'),
	 ('Гвардейск'),
	 ('Гдов'),
	 ('Геленджик'),
	 ('Георгиевск'),
	 ('Глазов'),
	 ('Голицыно'),
	 ('Горбатов');
INSERT INTO public.cities ("name") VALUES
	 ('Горно-Алтайск'),
	 ('Горнозаводск'),
	 ('Горняк'),
	 ('Городец'),
	 ('Городище'),
	 ('Городовиковск'),
	 ('Гороховец'),
	 ('Горячий Ключ'),
	 ('Грайворон'),
	 ('Гремячинск');
INSERT INTO public.cities ("name") VALUES
	 ('Грозный'),
	 ('Грязи'),
	 ('Грязовец'),
	 ('Губаха'),
	 ('Губкин'),
	 ('Губкинский'),
	 ('Гудермес'),
	 ('Гуково'),
	 ('Гулькевичи'),
	 ('Гурьевск');
INSERT INTO public.cities ("name") VALUES
	 ('Гусев'),
	 ('Гусиноозёрск'),
	 ('Гусь-Хрустальный'),
	 ('Давлеканово'),
	 ('Дагестанские Огни'),
	 ('Далматово'),
	 ('Дальнегорск'),
	 ('Дальнереченск'),
	 ('Данилов'),
	 ('Данков');
INSERT INTO public.cities ("name") VALUES
	 ('Дегтярск'),
	 ('Дедовск'),
	 ('Демидов'),
	 ('Дербент'),
	 ('Десногорск'),
	 ('Джанкойне призн.'),
	 ('Дзержинск'),
	 ('Дзержинский'),
	 ('Дивногорск'),
	 ('Дигора');
INSERT INTO public.cities ("name") VALUES
	 ('Димитровград'),
	 ('Дмитриев'),
	 ('Дмитров'),
	 ('Дмитровск'),
	 ('Дно'),
	 ('Добрянка'),
	 ('Долгопрудный'),
	 ('Долинск'),
	 ('Домодедово'),
	 ('Донецк');
INSERT INTO public.cities ("name") VALUES
	 ('Донской'),
	 ('Дорогобуж'),
	 ('Дрезна'),
	 ('Дубна'),
	 ('Дубовка'),
	 ('Дудинка'),
	 ('Духовщина'),
	 ('Дюртюли'),
	 ('Дятьково'),
	 ('Евпаторияне призн.');
INSERT INTO public.cities ("name") VALUES
	 ('Егорьевск'),
	 ('Ейск'),
	 ('Екатеринбург'),
	 ('Елабуга'),
	 ('Елец'),
	 ('Елизово'),
	 ('Ельня'),
	 ('Еманжелинск'),
	 ('Емва'),
	 ('Енисейск');
INSERT INTO public.cities ("name") VALUES
	 ('Ермолино'),
	 ('Ершов'),
	 ('Ессентуки'),
	 ('Ефремов'),
	 ('Железноводск'),
	 ('Железногорск'),
	 ('Железногорск-Илимский'),
	 ('Жердевка'),
	 ('Жигулёвск'),
	 ('Жиздра');
INSERT INTO public.cities ("name") VALUES
	 ('Жирновск'),
	 ('Жуков'),
	 ('Жуковка'),
	 ('Жуковский'),
	 ('Завитинск'),
	 ('Заводоуковск'),
	 ('Заволжск'),
	 ('Заволжье'),
	 ('Задонск'),
	 ('Заинск');
INSERT INTO public.cities ("name") VALUES
	 ('Закаменск'),
	 ('Заозёрный'),
	 ('Заозёрск'),
	 ('Западная Двина'),
	 ('Заполярный'),
	 ('Зарайск'),
	 ('Заречный'),
	 ('Заринск'),
	 ('Звенигово'),
	 ('Звенигород');
INSERT INTO public.cities ("name") VALUES
	 ('Зверево'),
	 ('Зеленогорск'),
	 ('Зеленоградск'),
	 ('Зеленодольск'),
	 ('Зеленокумск'),
	 ('Зерноград'),
	 ('Зея'),
	 ('Зима'),
	 ('Златоуст'),
	 ('Злынка');
INSERT INTO public.cities ("name") VALUES
	 ('Змеиногорск'),
	 ('Знаменск'),
	 ('Зубцов'),
	 ('Зуевка'),
	 ('Ивангород'),
	 ('Иваново'),
	 ('Ивантеевка'),
	 ('Ивдель'),
	 ('Игарка'),
	 ('Ижевск');
INSERT INTO public.cities ("name") VALUES
	 ('Избербаш'),
	 ('Изобильный'),
	 ('Иланский'),
	 ('Инза'),
	 ('Иннополис'),
	 ('Инсар'),
	 ('Инта'),
	 ('Ипатово'),
	 ('Ирбит'),
	 ('Иркутск');
INSERT INTO public.cities ("name") VALUES
	 ('Исилькуль'),
	 ('Искитим'),
	 ('Истра'),
	 ('Ишим'),
	 ('Ишимбай'),
	 ('Йошкар-Ола'),
	 ('Кадников'),
	 ('Казань'),
	 ('Калач'),
	 ('Калач-на-Дону');
INSERT INTO public.cities ("name") VALUES
	 ('Калачинск'),
	 ('Калининград'),
	 ('Калининск'),
	 ('Калтан'),
	 ('Калуга'),
	 ('Калязин'),
	 ('Камбарка'),
	 ('Каменка'),
	 ('Каменногорск'),
	 ('Каменск-Уральский');
INSERT INTO public.cities ("name") VALUES
	 ('Каменск-Шахтинский'),
	 ('Камень-на-Оби'),
	 ('Камешково'),
	 ('Камызяк'),
	 ('Камышин'),
	 ('Камышлов'),
	 ('Канаш'),
	 ('Кандалакша'),
	 ('Канск'),
	 ('Карабаново');
INSERT INTO public.cities ("name") VALUES
	 ('Карабаш'),
	 ('Карабулак'),
	 ('Карасук'),
	 ('Карачаевск'),
	 ('Карачев'),
	 ('Каргат'),
	 ('Каргополь'),
	 ('Карпинск'),
	 ('Карталы'),
	 ('Касимов');
INSERT INTO public.cities ("name") VALUES
	 ('Касли'),
	 ('Каспийск'),
	 ('Катав-Ивановск'),
	 ('Катайск'),
	 ('Качканар'),
	 ('Кашин'),
	 ('Кашира'),
	 ('Кедровый'),
	 ('Кемерово'),
	 ('Кемь');
INSERT INTO public.cities ("name") VALUES
	 ('Керчьне призн.'),
	 ('Кизел'),
	 ('Кизилюрт'),
	 ('Кизляр'),
	 ('Кимовск'),
	 ('Кимры'),
	 ('Кингисепп'),
	 ('Кинель'),
	 ('Кинешма'),
	 ('Киреевск');
INSERT INTO public.cities ("name") VALUES
	 ('Киренск'),
	 ('Киржач'),
	 ('Кириллов'),
	 ('Кириши'),
	 ('Киров'),
	 ('Кировград'),
	 ('Кирово-Чепецк'),
	 ('Кировск'),
	 ('Кирс'),
	 ('Кирсанов');
INSERT INTO public.cities ("name") VALUES
	 ('Киселёвск'),
	 ('Кисловодск'),
	 ('Клин'),
	 ('Клинцы'),
	 ('Княгинино'),
	 ('Ковдор'),
	 ('Ковров'),
	 ('Ковылкино'),
	 ('Когалым'),
	 ('Кодинск');
INSERT INTO public.cities ("name") VALUES
	 ('Козельск'),
	 ('Козловка'),
	 ('Козьмодемьянск'),
	 ('Кола'),
	 ('Кологрив'),
	 ('Коломна'),
	 ('Колпашево'),
	 ('Кольчугино'),
	 ('Коммунар'),
	 ('Комсомольск');
INSERT INTO public.cities ("name") VALUES
	 ('Комсомольск-на-Амуре'),
	 ('Конаково'),
	 ('Кондопога'),
	 ('Кондрово'),
	 ('Константиновск'),
	 ('Копейск'),
	 ('Кораблино'),
	 ('Кореновск'),
	 ('Коркино'),
	 ('Королёв');
INSERT INTO public.cities ("name") VALUES
	 ('Короча'),
	 ('Корсаков'),
	 ('Коряжма'),
	 ('Костерёво'),
	 ('Костомукша'),
	 ('Кострома'),
	 ('Котельники'),
	 ('Котельниково'),
	 ('Котельнич'),
	 ('Котлас');
INSERT INTO public.cities ("name") VALUES
	 ('Котово'),
	 ('Котовск'),
	 ('Кохма'),
	 ('Красавино'),
	 ('Красноармейск'),
	 ('Красновишерск'),
	 ('Красногорск'),
	 ('Краснодар'),
	 ('Краснозаводск'),
	 ('Краснознаменск');
INSERT INTO public.cities ("name") VALUES
	 ('Краснокаменск'),
	 ('Краснокамск'),
	 ('Красноперекопскне призн.'),
	 ('Краснослободск'),
	 ('Краснотурьинск'),
	 ('Красноуральск'),
	 ('Красноуфимск'),
	 ('Красноярск'),
	 ('Красный Кут'),
	 ('Красный Сулин');
INSERT INTO public.cities ("name") VALUES
	 ('Красный Холм'),
	 ('Кремёнки'),
	 ('Кропоткин'),
	 ('Крымск'),
	 ('Кстово'),
	 ('Кубинка'),
	 ('Кувандык'),
	 ('Кувшиново'),
	 ('Кудрово'),
	 ('Кудымкар');
INSERT INTO public.cities ("name") VALUES
	 ('Кузнецк'),
	 ('Куйбышев'),
	 ('Кукмор'),
	 ('Кулебаки'),
	 ('Кумертау'),
	 ('Кунгур'),
	 ('Купино'),
	 ('Курган'),
	 ('Курганинск'),
	 ('Курильск');
INSERT INTO public.cities ("name") VALUES
	 ('Курлово'),
	 ('Куровское'),
	 ('Курск'),
	 ('Куртамыш'),
	 ('Курчалой'),
	 ('Курчатов'),
	 ('Куса'),
	 ('Кушва'),
	 ('Кызыл'),
	 ('Кыштым');
INSERT INTO public.cities ("name") VALUES
	 ('Кяхта'),
	 ('Лабинск'),
	 ('Лабытнанги'),
	 ('Лагань'),
	 ('Ладушкин'),
	 ('Лаишево'),
	 ('Лакинск'),
	 ('Лангепас'),
	 ('Лахденпохья'),
	 ('Лебедянь');
INSERT INTO public.cities ("name") VALUES
	 ('Лениногорск'),
	 ('Ленинск'),
	 ('Ленинск-Кузнецкий'),
	 ('Ленск'),
	 ('Лермонтов'),
	 ('Лесной'),
	 ('Лесозаводск'),
	 ('Лесосибирск'),
	 ('Ливны'),
	 ('Ликино-Дулёво');
INSERT INTO public.cities ("name") VALUES
	 ('Липецк'),
	 ('Липки'),
	 ('Лиски'),
	 ('Лихославль'),
	 ('Лобня'),
	 ('Лодейное Поле'),
	 ('Лосино-Петровский'),
	 ('Луга'),
	 ('Луза'),
	 ('Лукоянов');
INSERT INTO public.cities ("name") VALUES
	 ('Луховицы'),
	 ('Лысково'),
	 ('Лысьва'),
	 ('Лыткарино'),
	 ('Льгов'),
	 ('Любань'),
	 ('Люберцы'),
	 ('Любим'),
	 ('Людиново'),
	 ('Лянтор');
INSERT INTO public.cities ("name") VALUES
	 ('Магадан'),
	 ('Магас'),
	 ('Магнитогорск'),
	 ('Майкоп'),
	 ('Майский'),
	 ('Макаров'),
	 ('Макарьев'),
	 ('Макушино'),
	 ('Малая Вишера'),
	 ('Малгобек');
INSERT INTO public.cities ("name") VALUES
	 ('Малмыж'),
	 ('Малоархангельск'),
	 ('Малоярославец'),
	 ('Мамадыш'),
	 ('Мамоново'),
	 ('Мантурово'),
	 ('Мариинск'),
	 ('Мариинский Посад'),
	 ('Маркс'),
	 ('Махачкала');
INSERT INTO public.cities ("name") VALUES
	 ('Мглин'),
	 ('Мегион'),
	 ('Медвежьегорск'),
	 ('Медногорск'),
	 ('Медынь'),
	 ('Межгорье'),
	 ('Междуреченск'),
	 ('Мезень'),
	 ('Меленки'),
	 ('Мелеуз');
INSERT INTO public.cities ("name") VALUES
	 ('Менделеевск'),
	 ('Мензелинск'),
	 ('Мещовск'),
	 ('Миасс'),
	 ('Микунь'),
	 ('Миллерово'),
	 ('Минеральные Воды'),
	 ('Минусинск'),
	 ('Миньяр'),
	 ('Мирный');
INSERT INTO public.cities ("name") VALUES
	 ('Михайлов'),
	 ('Михайловка'),
	 ('Михайловск'),
	 ('Мичуринск'),
	 ('Могоча'),
	 ('Можайск'),
	 ('Можга'),
	 ('Моздок'),
	 ('Мончегорск'),
	 ('Морозовск');
INSERT INTO public.cities ("name") VALUES
	 ('Моршанск'),
	 ('Мосальск'),
	 ('Москва'),
	 ('Муравленко'),
	 ('Мураши'),
	 ('Мурино'),
	 ('Мурманск'),
	 ('Муром'),
	 ('Мценск'),
	 ('Мыски');
INSERT INTO public.cities ("name") VALUES
	 ('Мытищи'),
	 ('Мышкин'),
	 ('Набережные Челны'),
	 ('Навашино'),
	 ('Наволоки'),
	 ('Надым'),
	 ('Назарово'),
	 ('Назрань'),
	 ('Называевск'),
	 ('Нальчик');
INSERT INTO public.cities ("name") VALUES
	 ('Нариманов'),
	 ('Наро-Фоминск'),
	 ('Нарткала'),
	 ('Нарьян-Мар'),
	 ('Находка'),
	 ('Невель'),
	 ('Невельск'),
	 ('Невинномысск'),
	 ('Невьянск'),
	 ('Нелидово');
INSERT INTO public.cities ("name") VALUES
	 ('Неман'),
	 ('Нерехта'),
	 ('Нерчинск'),
	 ('Нерюнгри'),
	 ('Нестеров'),
	 ('Нефтегорск'),
	 ('Нефтекамск'),
	 ('Нефтекумск'),
	 ('Нефтеюганск'),
	 ('Нея');
INSERT INTO public.cities ("name") VALUES
	 ('Нижневартовск'),
	 ('Нижнекамск'),
	 ('Нижнеудинск'),
	 ('Нижние Серги'),
	 ('Нижний Ломов'),
	 ('Нижний Новгород'),
	 ('Нижний Тагил'),
	 ('Нижняя Салда'),
	 ('Нижняя Тура'),
	 ('Николаевск');
INSERT INTO public.cities ("name") VALUES
	 ('Николаевск-на-Амуре'),
	 ('Никольск'),
	 ('Никольское'),
	 ('Новая Ладога'),
	 ('Новая Ляля'),
	 ('Новоалександровск'),
	 ('Новоалтайск'),
	 ('Новоаннинский'),
	 ('Нововоронеж'),
	 ('Новодвинск');
INSERT INTO public.cities ("name") VALUES
	 ('Новозыбков'),
	 ('Новокубанск'),
	 ('Новокузнецк'),
	 ('Новокуйбышевск'),
	 ('Новомичуринск'),
	 ('Новомосковск'),
	 ('Новопавловск'),
	 ('Новоржев'),
	 ('Новороссийск'),
	 ('Новосибирск');
INSERT INTO public.cities ("name") VALUES
	 ('Новосиль'),
	 ('Новосокольники'),
	 ('Новотроицк'),
	 ('Новоузенск'),
	 ('Новоульяновск'),
	 ('Новоуральск'),
	 ('Новохопёрск'),
	 ('Новочебоксарск'),
	 ('Новочеркасск'),
	 ('Новошахтинск');
INSERT INTO public.cities ("name") VALUES
	 ('Новый Оскол'),
	 ('Новый Уренгой'),
	 ('Ногинск'),
	 ('Нолинск'),
	 ('Норильск'),
	 ('Ноябрьск'),
	 ('Нурлат'),
	 ('Нытва'),
	 ('Нюрба'),
	 ('Нягань');
INSERT INTO public.cities ("name") VALUES
	 ('Нязепетровск'),
	 ('Няндома'),
	 ('Облучье'),
	 ('Обнинск'),
	 ('Обоянь'),
	 ('Обь'),
	 ('Одинцово'),
	 ('Озёрск'),
	 ('Озёры'),
	 ('Октябрьск');
INSERT INTO public.cities ("name") VALUES
	 ('Октябрьский'),
	 ('Окуловка'),
	 ('Олёкминск'),
	 ('Оленегорск'),
	 ('Олонец'),
	 ('Омск'),
	 ('Омутнинск'),
	 ('Онега'),
	 ('Опочка'),
	 ('Орёл');
INSERT INTO public.cities ("name") VALUES
	 ('Оренбург'),
	 ('Орехово-Зуево'),
	 ('Орлов'),
	 ('Орск'),
	 ('Оса'),
	 ('Осинники'),
	 ('Осташков'),
	 ('Остров'),
	 ('Островной'),
	 ('Острогожск');
INSERT INTO public.cities ("name") VALUES
	 ('Отрадное'),
	 ('Отрадный'),
	 ('Оха'),
	 ('Оханск'),
	 ('Очёр'),
	 ('Павлово'),
	 ('Павловск'),
	 ('Павловский Посад'),
	 ('Палласовка'),
	 ('Партизанск');
INSERT INTO public.cities ("name") VALUES
	 ('Певек'),
	 ('Пенза'),
	 ('Первомайск'),
	 ('Первоуральск'),
	 ('Перевоз'),
	 ('Пересвет'),
	 ('Переславль-Залесский'),
	 ('Пермь'),
	 ('Пестово'),
	 ('Петров Вал');
INSERT INTO public.cities ("name") VALUES
	 ('Петровск'),
	 ('Петровск-Забайкальский'),
	 ('Петрозаводск'),
	 ('Петропавловск-Камчатский'),
	 ('Петухово'),
	 ('Петушки'),
	 ('Печора'),
	 ('Печоры'),
	 ('Пикалёво'),
	 ('Пионерский');
INSERT INTO public.cities ("name") VALUES
	 ('Питкяранта'),
	 ('Плавск'),
	 ('Пласт'),
	 ('Плёс'),
	 ('Поворино'),
	 ('Подольск'),
	 ('Подпорожье'),
	 ('Покачи'),
	 ('Покров'),
	 ('Покровск');
INSERT INTO public.cities ("name") VALUES
	 ('Полевской'),
	 ('Полесск'),
	 ('Полысаево'),
	 ('Полярные Зори'),
	 ('Полярный'),
	 ('Поронайск'),
	 ('Порхов'),
	 ('Похвистнево'),
	 ('Почеп'),
	 ('Починок');
INSERT INTO public.cities ("name") VALUES
	 ('Пошехонье'),
	 ('Правдинск'),
	 ('Приволжск'),
	 ('Приморск'),
	 ('Приморско-Ахтарск'),
	 ('Приозерск'),
	 ('Прокопьевск'),
	 ('Пролетарск'),
	 ('Протвино'),
	 ('Прохладный');
INSERT INTO public.cities ("name") VALUES
	 ('Псков'),
	 ('Пугачёв'),
	 ('Пудож'),
	 ('Пустошка'),
	 ('Пучеж'),
	 ('Пушкино'),
	 ('Пущино'),
	 ('Пыталово'),
	 ('Пыть-Ях'),
	 ('Пятигорск');
INSERT INTO public.cities ("name") VALUES
	 ('Радужный'),
	 ('Райчихинск'),
	 ('Раменское'),
	 ('Рассказово'),
	 ('Ревда'),
	 ('Реж'),
	 ('Реутов'),
	 ('Ржев'),
	 ('Родники'),
	 ('Рославль');
INSERT INTO public.cities ("name") VALUES
	 ('Россошь'),
	 ('Ростов-на-Дону'),
	 ('Ростов'),
	 ('Рошаль'),
	 ('Ртищево'),
	 ('Рубцовск'),
	 ('Рудня'),
	 ('Руза'),
	 ('Рузаевка'),
	 ('Рыбинск');
INSERT INTO public.cities ("name") VALUES
	 ('Рыбное'),
	 ('Рыльск'),
	 ('Ряжск'),
	 ('Рязань'),
	 ('Сакине призн.'),
	 ('Салават'),
	 ('Салаир'),
	 ('Салехард'),
	 ('Сальск'),
	 ('Самара');
INSERT INTO public.cities ("name") VALUES
	 ('Санкт-Петербург'),
	 ('Саранск'),
	 ('Сарапул'),
	 ('Саратов'),
	 ('Саров'),
	 ('Сасово'),
	 ('Сатка'),
	 ('Сафоново'),
	 ('Саяногорск'),
	 ('Саянск');
INSERT INTO public.cities ("name") VALUES
	 ('Светлогорск'),
	 ('Светлоград'),
	 ('Светлый'),
	 ('Светогорск'),
	 ('Свирск'),
	 ('Свободный'),
	 ('Себеж'),
	 ('Севастопольне призн.'),
	 ('Северо-Курильск'),
	 ('Северобайкальск');
INSERT INTO public.cities ("name") VALUES
	 ('Северодвинск'),
	 ('Североморск'),
	 ('Североуральск'),
	 ('Северск'),
	 ('Севск'),
	 ('Сегежа'),
	 ('Сельцо'),
	 ('Семёнов'),
	 ('Семикаракорск'),
	 ('Семилуки');
INSERT INTO public.cities ("name") VALUES
	 ('Сенгилей'),
	 ('Серафимович'),
	 ('Сергач'),
	 ('Сергиев Посад'),
	 ('Сердобск'),
	 ('Серов'),
	 ('Серпухов'),
	 ('Сертолово'),
	 ('Сибай'),
	 ('Сим');
INSERT INTO public.cities ("name") VALUES
	 ('Симферопольне призн.'),
	 ('Сковородино'),
	 ('Скопин'),
	 ('Славгород'),
	 ('Славск'),
	 ('Славянск-на-Кубани'),
	 ('Сланцы'),
	 ('Слободской'),
	 ('Слюдянка'),
	 ('Смоленск');
INSERT INTO public.cities ("name") VALUES
	 ('Снежинск'),
	 ('Снежногорск'),
	 ('Собинка'),
	 ('Советск'),
	 ('Советская Гавань'),
	 ('Советский'),
	 ('Сокол'),
	 ('Солигалич'),
	 ('Соликамск'),
	 ('Солнечногорск');
INSERT INTO public.cities ("name") VALUES
	 ('Соль-Илецк'),
	 ('Сольвычегодск'),
	 ('Сольцы'),
	 ('Сорочинск'),
	 ('Сорск'),
	 ('Сортавала'),
	 ('Сосенский'),
	 ('Сосновка'),
	 ('Сосновоборск'),
	 ('Сосновый Бор');
INSERT INTO public.cities ("name") VALUES
	 ('Сосногорск'),
	 ('Сочи'),
	 ('Спас-Деменск'),
	 ('Спас-Клепики'),
	 ('Спасск'),
	 ('Спасск-Дальний'),
	 ('Спасск-Рязанский'),
	 ('Среднеколымск'),
	 ('Среднеуральск'),
	 ('Сретенск');
INSERT INTO public.cities ("name") VALUES
	 ('Ставрополь'),
	 ('Старая Купавна'),
	 ('Старая Русса'),
	 ('Старица'),
	 ('Стародуб'),
	 ('Старый Крымне призн.'),
	 ('Старый Оскол'),
	 ('Стерлитамак'),
	 ('Стрежевой'),
	 ('Строитель');
INSERT INTO public.cities ("name") VALUES
	 ('Струнино'),
	 ('Ступино'),
	 ('Суворов'),
	 ('Судакне призн.'),
	 ('Суджа'),
	 ('Судогда'),
	 ('Суздаль'),
	 ('Сунжа'),
	 ('Суоярви'),
	 ('Сураж');
INSERT INTO public.cities ("name") VALUES
	 ('Сургут'),
	 ('Суровикино'),
	 ('Сурск'),
	 ('Сусуман'),
	 ('Сухиничи'),
	 ('Сухой Лог'),
	 ('Сызрань'),
	 ('Сыктывкар'),
	 ('Сысерть'),
	 ('Сычёвка');
INSERT INTO public.cities ("name") VALUES
	 ('Сясьстрой'),
	 ('Тавда'),
	 ('Таганрог'),
	 ('Тайга'),
	 ('Тайшет'),
	 ('Талдом'),
	 ('Талица'),
	 ('Тамбов'),
	 ('Тара'),
	 ('Тарко-Сале');
INSERT INTO public.cities ("name") VALUES
	 ('Таруса'),
	 ('Татарск'),
	 ('Таштагол'),
	 ('Тверь'),
	 ('Теберда'),
	 ('Тейково'),
	 ('Темников'),
	 ('Темрюк'),
	 ('Терек'),
	 ('Тетюши');
INSERT INTO public.cities ("name") VALUES
	 ('Тимашёвск'),
	 ('Тихвин'),
	 ('Тихорецк'),
	 ('Тобольск'),
	 ('Тогучин'),
	 ('Тольятти'),
	 ('Томари'),
	 ('Томмот'),
	 ('Томск'),
	 ('Топки');
INSERT INTO public.cities ("name") VALUES
	 ('Торжок'),
	 ('Торопец'),
	 ('Тосно'),
	 ('Тотьма'),
	 ('Трёхгорный'),
	 ('Троицк'),
	 ('Трубчевск'),
	 ('Туапсе'),
	 ('Туймазы'),
	 ('Тула');
INSERT INTO public.cities ("name") VALUES
	 ('Тулун'),
	 ('Туран'),
	 ('Туринск'),
	 ('Тутаев'),
	 ('Тында'),
	 ('Тырныауз'),
	 ('Тюкалинск'),
	 ('Тюмень'),
	 ('Уварово'),
	 ('Углегорск');
INSERT INTO public.cities ("name") VALUES
	 ('Углич'),
	 ('Удачный'),
	 ('Удомля'),
	 ('Ужур'),
	 ('Узловая'),
	 ('Улан-Удэ'),
	 ('Ульяновск'),
	 ('Унеча'),
	 ('Урай'),
	 ('Урень');
INSERT INTO public.cities ("name") VALUES
	 ('Уржум'),
	 ('Урус-Мартан'),
	 ('Урюпинск'),
	 ('Усинск'),
	 ('Усмань'),
	 ('Усолье-Сибирское'),
	 ('Усолье'),
	 ('Уссурийск'),
	 ('Усть-Джегута'),
	 ('Усть-Илимск');
INSERT INTO public.cities ("name") VALUES
	 ('Усть-Катав'),
	 ('Усть-Кут'),
	 ('Усть-Лабинск'),
	 ('Устюжна'),
	 ('Уфа'),
	 ('Ухта'),
	 ('Учалы'),
	 ('Уяр'),
	 ('Фатеж'),
	 ('Феодосияне призн.');
INSERT INTO public.cities ("name") VALUES
	 ('Фокино'),
	 ('Фролово'),
	 ('Фрязино'),
	 ('Фурманов'),
	 ('Хабаровск'),
	 ('Хадыженск'),
	 ('Ханты-Мансийск'),
	 ('Харабали'),
	 ('Харовск'),
	 ('Хасавюрт');
INSERT INTO public.cities ("name") VALUES
	 ('Хвалынск'),
	 ('Хилок'),
	 ('Химки'),
	 ('Холм'),
	 ('Холмск'),
	 ('Хотьково'),
	 ('Цивильск'),
	 ('Цимлянск'),
	 ('Циолковский'),
	 ('Чадан');
INSERT INTO public.cities ("name") VALUES
	 ('Чайковский'),
	 ('Чапаевск'),
	 ('Чаплыгин'),
	 ('Чебаркуль'),
	 ('Чебоксары'),
	 ('Чегем'),
	 ('Чекалин'),
	 ('Челябинск'),
	 ('Чердынь'),
	 ('Черемхово');
INSERT INTO public.cities ("name") VALUES
	 ('Черепаново'),
	 ('Череповец'),
	 ('Черкесск'),
	 ('Чёрмоз'),
	 ('Черноголовка'),
	 ('Черногорск'),
	 ('Чернушка'),
	 ('Черняховск'),
	 ('Чехов'),
	 ('Чистополь');
INSERT INTO public.cities ("name") VALUES
	 ('Чита'),
	 ('Чкаловск'),
	 ('Чудово'),
	 ('Чулым'),
	 ('Чусовой'),
	 ('Чухлома'),
	 ('Шагонар'),
	 ('Шадринск'),
	 ('Шали'),
	 ('Шарыпово');
INSERT INTO public.cities ("name") VALUES
	 ('Шарья'),
	 ('Шатура'),
	 ('Шахты'),
	 ('Шахунья'),
	 ('Шацк'),
	 ('Шебекино'),
	 ('Шелехов'),
	 ('Шенкурск'),
	 ('Шилка'),
	 ('Шимановск');
INSERT INTO public.cities ("name") VALUES
	 ('Шиханы'),
	 ('Шлиссельбург'),
	 ('Шумерля'),
	 ('Шумиха'),
	 ('Шуя'),
	 ('Щёкино'),
	 ('Щёлкиноне призн.'),
	 ('Щёлково'),
	 ('Щигры'),
	 ('Щучье');
INSERT INTO public.cities ("name") VALUES
	 ('Электрогорск'),
	 ('Электросталь'),
	 ('Электроугли'),
	 ('Элиста'),
	 ('Энгельс'),
	 ('Эртиль'),
	 ('Югорск'),
	 ('Южа'),
	 ('Южно-Сахалинск'),
	 ('Южно-Сухокумск');
INSERT INTO public.cities ("name") VALUES
	 ('Южноуральск'),
	 ('Юрга'),
	 ('Юрьев-Польский'),
	 ('Юрьевец'),
	 ('Юрюзань'),
	 ('Юхнов'),
	 ('Ядрин'),
	 ('Якутск'),
	 ('Ялтане призн.'),
	 ('Ялуторовск');
INSERT INTO public.cities ("name") VALUES
	 ('Янаул'),
	 ('Яранск'),
	 ('Яровое'),
	 ('Ярославль'),
	 ('Ярцево'),
	 ('Ясногорск'),
	 ('Ясный'),
	 ('Яхрома');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1'),
	 ('image2'),
	 ('image54'),
	 ('image4'),
	 ('image5'),
	 ('image6'),
	 ('image7'),
	 ('image8'),
	 ('image9'),
	 ('image10');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image11'),
	 ('image55'),
	 ('image62'),
	 ('image13'),
	 ('image135'),
	 ('image14'),
	 ('image15'),
	 ('image182'),
	 ('image16'),
	 ('');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image17'),
	 ('image18'),
	 ('image19'),
	 ('image20'),
	 ('image21'),
	 ('image22'),
	 ('image23'),
	 ('image24'),
	 ('image25'),
	 ('image26');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image27'),
	 ('image28'),
	 ('image29'),
	 ('image30'),
	 ('image31'),
	 ('image32'),
	 ('image33'),
	 ('image34'),
	 ('image35'),
	 ('image36');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image37'),
	 ('image38'),
	 ('image39'),
	 ('image40'),
	 ('image41'),
	 ('image42'),
	 ('image43'),
	 ('image44'),
	 ('image45'),
	 ('image46');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image47'),
	 ('image48'),
	 ('image49'),
	 ('image50'),
	 ('image51'),
	 ('image52'),
	 ('image53'),
	 ('image56'),
	 ('image57'),
	 ('image58');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image59'),
	 ('image60'),
	 ('image61'),
	 ('image63'),
	 ('image64'),
	 ('image65'),
	 ('image66'),
	 ('image67'),
	 ('image68'),
	 ('image69');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image70'),
	 ('image71'),
	 ('image72'),
	 ('image73'),
	 ('image74'),
	 ('image75'),
	 ('image76'),
	 ('image77'),
	 ('image78'),
	 ('image79');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image80'),
	 ('image81'),
	 ('image82'),
	 ('image83'),
	 ('image84'),
	 ('image85'),
	 ('image86'),
	 ('image87'),
	 ('image88'),
	 ('image89');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image90'),
	 ('image91'),
	 ('image92'),
	 ('image93'),
	 ('image94'),
	 ('image95'),
	 ('image96'),
	 ('image97'),
	 ('image98'),
	 ('image99');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image100'),
	 ('image101'),
	 ('image102'),
	 ('image103'),
	 ('image104'),
	 ('image105'),
	 ('image106'),
	 ('image107'),
	 ('image108'),
	 ('image109');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image110'),
	 ('image111'),
	 ('image112'),
	 ('image113'),
	 ('image114'),
	 ('image115'),
	 ('image116'),
	 ('image117'),
	 ('image118'),
	 ('image119');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image120'),
	 ('image121'),
	 ('image122'),
	 ('image123'),
	 ('image124'),
	 ('image125'),
	 ('image126'),
	 ('image127'),
	 ('image128'),
	 ('image129');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image130'),
	 ('image131'),
	 ('image132'),
	 ('image133'),
	 ('image134'),
	 ('image136'),
	 ('image137'),
	 ('image138'),
	 ('image139'),
	 ('image140');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image141'),
	 ('image142'),
	 ('image143'),
	 ('image144'),
	 ('image145'),
	 ('image146'),
	 ('image147'),
	 ('image148'),
	 ('image149'),
	 ('image150');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image151'),
	 ('image152'),
	 ('image153'),
	 ('image154'),
	 ('image155'),
	 ('image156'),
	 ('image157'),
	 ('image158'),
	 ('image159'),
	 ('image160');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image161'),
	 ('image162'),
	 ('image163'),
	 ('image164'),
	 ('image165'),
	 ('image166'),
	 ('image167'),
	 ('image168'),
	 ('image169'),
	 ('image170');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image171'),
	 ('image172'),
	 ('image173'),
	 ('image174'),
	 ('image175'),
	 ('image176'),
	 ('image177'),
	 ('image178'),
	 ('image179'),
	 ('image180');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image181'),
	 ('image183'),
	 ('image184'),
	 ('image185'),
	 ('image186'),
	 ('image187'),
	 ('image188'),
	 ('image189'),
	 ('image190'),
	 ('image191');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image192'),
	 ('image193'),
	 ('image194'),
	 ('image195'),
	 ('image196'),
	 ('image197'),
	 ('image198'),
	 ('image199'),
	 ('image200'),
	 ('image201');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image202'),
	 ('image203'),
	 ('image204'),
	 ('image205'),
	 ('image206'),
	 ('image207'),
	 ('image208'),
	 ('image209'),
	 ('image210'),
	 ('image211');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image212'),
	 ('image213'),
	 ('image214'),
	 ('image215'),
	 ('image216'),
	 ('image217'),
	 ('image218'),
	 ('image219'),
	 ('image220'),
	 ('image221');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image222'),
	 ('image223'),
	 ('image224'),
	 ('image225'),
	 ('image226'),
	 ('image227'),
	 ('image228'),
	 ('image229'),
	 ('image230'),
	 ('image231');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image232'),
	 ('image233'),
	 ('image234'),
	 ('image235'),
	 ('image236'),
	 ('image237'),
	 ('image238'),
	 ('image239'),
	 ('image240'),
	 ('image241');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image242'),
	 ('image243'),
	 ('image244'),
	 ('image245'),
	 ('image246'),
	 ('image247'),
	 ('image248'),
	 ('image249'),
	 ('image250'),
	 ('image251');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image252'),
	 ('image253'),
	 ('image254'),
	 ('image255'),
	 ('image256'),
	 ('image257'),
	 ('image258'),
	 ('image259'),
	 ('image260'),
	 ('image261');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image262'),
	 ('image263'),
	 ('image264'),
	 ('image265'),
	 ('image266'),
	 ('image267'),
	 ('image268'),
	 ('image269'),
	 ('image270'),
	 ('image271');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image272'),
	 ('image273'),
	 ('image274'),
	 ('image275'),
	 ('image276'),
	 ('image277'),
	 ('image278'),
	 ('image279'),
	 ('image280'),
	 ('image281');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image282'),
	 ('image283'),
	 ('image284'),
	 ('image285'),
	 ('image286'),
	 ('image287'),
	 ('image288'),
	 ('image289'),
	 ('image290'),
	 ('image291');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image292'),
	 ('image293'),
	 ('image294'),
	 ('image295'),
	 ('image296'),
	 ('image297'),
	 ('image298'),
	 ('image299'),
	 ('image300'),
	 ('image301');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image302'),
	 ('image303'),
	 ('image304'),
	 ('image305'),
	 ('image306'),
	 ('image307'),
	 ('image308'),
	 ('image309'),
	 ('image310'),
	 ('image311');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image312'),
	 ('image313'),
	 ('image314'),
	 ('image315'),
	 ('image316'),
	 ('image317'),
	 ('image318'),
	 ('image319'),
	 ('image320'),
	 ('image321');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image322'),
	 ('image323'),
	 ('image324'),
	 ('image325'),
	 ('image326'),
	 ('image327'),
	 ('image328'),
	 ('image329'),
	 ('image330'),
	 ('image331');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image332'),
	 ('image333'),
	 ('image334'),
	 ('image335'),
	 ('image336'),
	 ('image337'),
	 ('image338'),
	 ('image339'),
	 ('image340'),
	 ('image341');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image342'),
	 ('image343'),
	 ('image344'),
	 ('image345'),
	 ('image346'),
	 ('image347'),
	 ('image348'),
	 ('image349'),
	 ('image350'),
	 ('image351');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image352'),
	 ('image353'),
	 ('image354'),
	 ('image355'),
	 ('image356'),
	 ('image357'),
	 ('image358'),
	 ('image359'),
	 ('image360'),
	 ('image361');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image362'),
	 ('image363'),
	 ('image364'),
	 ('image365'),
	 ('image366'),
	 ('image367'),
	 ('image368'),
	 ('image369'),
	 ('image370'),
	 ('image371');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image372'),
	 ('image373'),
	 ('image374'),
	 ('image375'),
	 ('image376'),
	 ('image377'),
	 ('image378'),
	 ('image379'),
	 ('image380'),
	 ('image381');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image382'),
	 ('image383'),
	 ('image384'),
	 ('image385'),
	 ('image386'),
	 ('image387'),
	 ('image388'),
	 ('image389'),
	 ('image390'),
	 ('image391');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image392'),
	 ('image393'),
	 ('image394'),
	 ('image395'),
	 ('image396'),
	 ('image397'),
	 ('image398'),
	 ('image399'),
	 ('image400'),
	 ('image401');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image402'),
	 ('image403'),
	 ('image404'),
	 ('image405'),
	 ('image406'),
	 ('image407'),
	 ('image408'),
	 ('image409'),
	 ('image410'),
	 ('image411');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image412'),
	 ('image413'),
	 ('image414'),
	 ('image415'),
	 ('image416'),
	 ('image417'),
	 ('image418'),
	 ('image419'),
	 ('image420'),
	 ('image421');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image422'),
	 ('image423'),
	 ('image424'),
	 ('image425'),
	 ('image426'),
	 ('image427'),
	 ('image428'),
	 ('image429'),
	 ('image430'),
	 ('image431');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image432'),
	 ('image433'),
	 ('image434'),
	 ('image435'),
	 ('image436'),
	 ('image437'),
	 ('image438'),
	 ('image439'),
	 ('image440'),
	 ('image441');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image442'),
	 ('image443'),
	 ('image444'),
	 ('image445'),
	 ('image446'),
	 ('image447'),
	 ('image448'),
	 ('image449'),
	 ('image450'),
	 ('image451');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image452'),
	 ('image453'),
	 ('image454'),
	 ('image455'),
	 ('image456'),
	 ('image457'),
	 ('image458'),
	 ('image459'),
	 ('image460'),
	 ('image461');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image462'),
	 ('image463'),
	 ('image464'),
	 ('image465'),
	 ('image466'),
	 ('image467'),
	 ('image468'),
	 ('image469'),
	 ('image470'),
	 ('image471');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image472'),
	 ('image473'),
	 ('image474'),
	 ('image475'),
	 ('image476'),
	 ('image477'),
	 ('image478'),
	 ('image479'),
	 ('image480'),
	 ('image481');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image482'),
	 ('image483'),
	 ('image484'),
	 ('image485'),
	 ('image486'),
	 ('image487'),
	 ('image488'),
	 ('image489'),
	 ('image490'),
	 ('image491');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image492'),
	 ('image493'),
	 ('image494'),
	 ('image495'),
	 ('image496'),
	 ('image497'),
	 ('image498'),
	 ('image499'),
	 ('image500'),
	 ('image501');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image502'),
	 ('image503'),
	 ('image504'),
	 ('image505'),
	 ('image506'),
	 ('image507'),
	 ('image508'),
	 ('image509'),
	 ('image510'),
	 ('image511');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image512'),
	 ('image513'),
	 ('image514'),
	 ('image515'),
	 ('image516'),
	 ('image517'),
	 ('image518'),
	 ('image519'),
	 ('image520'),
	 ('image521');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image522'),
	 ('image523'),
	 ('image524'),
	 ('image525'),
	 ('image526'),
	 ('image527'),
	 ('image528'),
	 ('image529'),
	 ('image530'),
	 ('image531');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image532'),
	 ('image533'),
	 ('image534'),
	 ('image535'),
	 ('image536'),
	 ('image537'),
	 ('image538'),
	 ('image539'),
	 ('image540'),
	 ('image541');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image542'),
	 ('image543'),
	 ('image544'),
	 ('image545'),
	 ('image546'),
	 ('image547'),
	 ('image548'),
	 ('image549'),
	 ('image550'),
	 ('image551');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image552'),
	 ('image553'),
	 ('image554'),
	 ('image555'),
	 ('image556'),
	 ('image557'),
	 ('image558'),
	 ('image559'),
	 ('image560'),
	 ('image561');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image562'),
	 ('image563'),
	 ('image564'),
	 ('image565'),
	 ('image566'),
	 ('image567'),
	 ('image568'),
	 ('image569'),
	 ('image570'),
	 ('image571');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image572'),
	 ('image573'),
	 ('image574'),
	 ('image575'),
	 ('image576'),
	 ('image577'),
	 ('image578'),
	 ('image579'),
	 ('image580'),
	 ('image581');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image582'),
	 ('image583'),
	 ('image584'),
	 ('image585'),
	 ('image586'),
	 ('image587'),
	 ('image588'),
	 ('image589'),
	 ('image590'),
	 ('image591');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image592'),
	 ('image593'),
	 ('image594'),
	 ('image595'),
	 ('image596'),
	 ('image597'),
	 ('image598'),
	 ('image599'),
	 ('image600'),
	 ('image601');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image602'),
	 ('image603'),
	 ('image604'),
	 ('image605'),
	 ('image606'),
	 ('image607'),
	 ('image608'),
	 ('image609'),
	 ('image610'),
	 ('image611');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image612'),
	 ('image613'),
	 ('image614'),
	 ('image615'),
	 ('image616'),
	 ('image617'),
	 ('image618'),
	 ('image619'),
	 ('image620'),
	 ('image621');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image622'),
	 ('image623'),
	 ('image624'),
	 ('image625'),
	 ('image626'),
	 ('image627'),
	 ('image628'),
	 ('image629'),
	 ('image630'),
	 ('image631');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image632'),
	 ('image633'),
	 ('image634'),
	 ('image635'),
	 ('image636'),
	 ('image637'),
	 ('image638'),
	 ('image639'),
	 ('image640'),
	 ('image641');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image642'),
	 ('image643'),
	 ('image644'),
	 ('image645'),
	 ('image646'),
	 ('image647'),
	 ('image648'),
	 ('image649'),
	 ('image650'),
	 ('image651');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image652'),
	 ('image653'),
	 ('image654'),
	 ('image655'),
	 ('image656'),
	 ('image657'),
	 ('image658'),
	 ('image659'),
	 ('image660'),
	 ('image661');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image662'),
	 ('image663'),
	 ('image664'),
	 ('image665'),
	 ('image666'),
	 ('image667'),
	 ('image668'),
	 ('image669'),
	 ('image670'),
	 ('image671');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image672'),
	 ('image673'),
	 ('image674'),
	 ('image675'),
	 ('image676'),
	 ('image677'),
	 ('image678'),
	 ('image679'),
	 ('image680'),
	 ('image681');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image682'),
	 ('image683'),
	 ('image684'),
	 ('image685'),
	 ('image686'),
	 ('image687'),
	 ('image688'),
	 ('image689'),
	 ('image690'),
	 ('image691');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image692'),
	 ('image693'),
	 ('image694'),
	 ('image695'),
	 ('image696'),
	 ('image697'),
	 ('image698'),
	 ('image699'),
	 ('image700'),
	 ('image701');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image702'),
	 ('image703'),
	 ('image704'),
	 ('image705'),
	 ('image706'),
	 ('image707'),
	 ('image708'),
	 ('image709'),
	 ('image710'),
	 ('image711');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image712'),
	 ('image713'),
	 ('image714'),
	 ('image715'),
	 ('image716'),
	 ('image717'),
	 ('image718'),
	 ('image719'),
	 ('image720'),
	 ('image721');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image722'),
	 ('image723'),
	 ('image724'),
	 ('image725'),
	 ('image726'),
	 ('image727'),
	 ('image728'),
	 ('image729'),
	 ('image730'),
	 ('image731');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image732'),
	 ('image733'),
	 ('image734'),
	 ('image735'),
	 ('image736'),
	 ('image737'),
	 ('image738'),
	 ('image739'),
	 ('image740'),
	 ('image741');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image742'),
	 ('image743'),
	 ('image744'),
	 ('image745'),
	 ('image746'),
	 ('image747'),
	 ('image748'),
	 ('image749'),
	 ('image750'),
	 ('image751');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image752'),
	 ('image753'),
	 ('image754'),
	 ('image755'),
	 ('image756'),
	 ('image757'),
	 ('image758'),
	 ('image759'),
	 ('image760'),
	 ('image761');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image762'),
	 ('image763'),
	 ('image764'),
	 ('image765'),
	 ('image766'),
	 ('image767'),
	 ('image768'),
	 ('image769'),
	 ('image770'),
	 ('image771');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image772'),
	 ('image773'),
	 ('image774'),
	 ('image775'),
	 ('image776'),
	 ('image777'),
	 ('image778'),
	 ('image779'),
	 ('image780'),
	 ('image781');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image782'),
	 ('image783'),
	 ('image784'),
	 ('image785'),
	 ('image786'),
	 ('image787'),
	 ('image788'),
	 ('image789'),
	 ('image790'),
	 ('image791');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image792'),
	 ('image793'),
	 ('image794'),
	 ('image795'),
	 ('image796'),
	 ('image797'),
	 ('image798'),
	 ('image799'),
	 ('image800'),
	 ('image801');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image802'),
	 ('image803'),
	 ('image804'),
	 ('image805'),
	 ('image806'),
	 ('image807'),
	 ('image808'),
	 ('image809'),
	 ('image810'),
	 ('image811');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image812'),
	 ('image813'),
	 ('image814'),
	 ('image815'),
	 ('image816'),
	 ('image817'),
	 ('image818'),
	 ('image819'),
	 ('image820'),
	 ('image821');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image822'),
	 ('image823'),
	 ('image824'),
	 ('image825'),
	 ('image826'),
	 ('image827'),
	 ('image828'),
	 ('image829'),
	 ('image830'),
	 ('image831');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image832'),
	 ('image833'),
	 ('image834'),
	 ('image835'),
	 ('image836'),
	 ('image837'),
	 ('image838'),
	 ('image839'),
	 ('image840'),
	 ('image841');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image842'),
	 ('image843'),
	 ('image844'),
	 ('image845'),
	 ('image846'),
	 ('image847'),
	 ('image848'),
	 ('image849'),
	 ('image850'),
	 ('image851');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image852'),
	 ('image853'),
	 ('image854'),
	 ('image855'),
	 ('image856'),
	 ('image857'),
	 ('image858'),
	 ('image859'),
	 ('image860'),
	 ('image861');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image862'),
	 ('image863'),
	 ('image864'),
	 ('image865'),
	 ('image866'),
	 ('image867'),
	 ('image868'),
	 ('image869'),
	 ('image870'),
	 ('image871');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image872'),
	 ('image873'),
	 ('image874'),
	 ('image875'),
	 ('image876'),
	 ('image877'),
	 ('image878'),
	 ('image879'),
	 ('image880'),
	 ('image881');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image882'),
	 ('image883'),
	 ('image884'),
	 ('image885'),
	 ('image886'),
	 ('image887'),
	 ('image888'),
	 ('image889'),
	 ('image890'),
	 ('image891');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image892'),
	 ('image893'),
	 ('image894'),
	 ('image895'),
	 ('image896'),
	 ('image897'),
	 ('image898'),
	 ('image899'),
	 ('image900'),
	 ('image901');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image902'),
	 ('image903'),
	 ('image904'),
	 ('image905'),
	 ('image906'),
	 ('image907'),
	 ('image908'),
	 ('image909'),
	 ('image910'),
	 ('image911');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image912'),
	 ('image913'),
	 ('image914'),
	 ('image915'),
	 ('image916'),
	 ('image917'),
	 ('image918'),
	 ('image919'),
	 ('image920'),
	 ('image921');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image922'),
	 ('image923'),
	 ('image924'),
	 ('image925'),
	 ('image926'),
	 ('image927'),
	 ('image928'),
	 ('image929'),
	 ('image930'),
	 ('image931');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image932'),
	 ('image933'),
	 ('image934'),
	 ('image935'),
	 ('image936'),
	 ('image937'),
	 ('image938'),
	 ('image939'),
	 ('image940'),
	 ('image941');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image942'),
	 ('image943'),
	 ('image944'),
	 ('image945'),
	 ('image946'),
	 ('image947'),
	 ('image948'),
	 ('image949'),
	 ('image950'),
	 ('image951');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image952'),
	 ('image953'),
	 ('image954'),
	 ('image955'),
	 ('image956'),
	 ('image957'),
	 ('image958'),
	 ('image959'),
	 ('image960'),
	 ('image961');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image962'),
	 ('image963'),
	 ('image964'),
	 ('image965'),
	 ('image966'),
	 ('image967'),
	 ('image968'),
	 ('image969'),
	 ('image970'),
	 ('image971');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image972'),
	 ('image973'),
	 ('image974'),
	 ('image975'),
	 ('image976'),
	 ('image977'),
	 ('image978'),
	 ('image979'),
	 ('image980'),
	 ('image981');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image982'),
	 ('image983'),
	 ('image984'),
	 ('image985'),
	 ('image986'),
	 ('image987'),
	 ('image988'),
	 ('image989'),
	 ('image990'),
	 ('image991');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image992'),
	 ('image993'),
	 ('image994'),
	 ('image995'),
	 ('image996'),
	 ('image997'),
	 ('image998'),
	 ('image999'),
	 ('image1000'),
	 ('image1001');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1002'),
	 ('image1003'),
	 ('image1004'),
	 ('image1005'),
	 ('image1006'),
	 ('image1007'),
	 ('image1008'),
	 ('image1009'),
	 ('image1010'),
	 ('image1011');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1012'),
	 ('image1013'),
	 ('image1014'),
	 ('image1015'),
	 ('image1016'),
	 ('image1017'),
	 ('image1018'),
	 ('image1019'),
	 ('image1020'),
	 ('image1021');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1022'),
	 ('image1023'),
	 ('image1024'),
	 ('image1025'),
	 ('image1026'),
	 ('image1027'),
	 ('image1028'),
	 ('image1029'),
	 ('image1030'),
	 ('image1031');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1032'),
	 ('image1033'),
	 ('image1034'),
	 ('image1035'),
	 ('image1036'),
	 ('image1037'),
	 ('image1038'),
	 ('image1039'),
	 ('image1040'),
	 ('image1041');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1042'),
	 ('image1043'),
	 ('image1044'),
	 ('image1045'),
	 ('image1046'),
	 ('image1047'),
	 ('image1048'),
	 ('image1049'),
	 ('image1050'),
	 ('image1051');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1052'),
	 ('image1053'),
	 ('image1054'),
	 ('image1055'),
	 ('image1056'),
	 ('image1057'),
	 ('image1058'),
	 ('image1059'),
	 ('image1060'),
	 ('image1061');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1062'),
	 ('image1063'),
	 ('image1064'),
	 ('image1065'),
	 ('image1066'),
	 ('image1067'),
	 ('image1068'),
	 ('image1069'),
	 ('image1070'),
	 ('image1071');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1072'),
	 ('image1073'),
	 ('image1074'),
	 ('image1075'),
	 ('image1076'),
	 ('image1077'),
	 ('image1078'),
	 ('image1079'),
	 ('image1080'),
	 ('image1081');
INSERT INTO public.city_emblems (emblem) VALUES
	 ('image1082'),
	 ('image1083'),
	 ('image1084');
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Абхазия','Abkhazia','AB',895),
	 ('Австралия','Australia','AU',36),
	 ('Австрия','Austria','AT',40),
	 ('Азербайджан','Azerbaijan','AZ',31),
	 ('Албания','Albania','AL',8),
	 ('Алжир','Algeria','DZ',12),
	 ('Американское Самоа','American Samoa','AS',16),
	 ('Ангилья','Anguilla','AI',660),
	 ('Ангола','Angola','AO',24),
	 ('Андорра','Andorra','AD',20);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Антарктида','Antarctica','AQ',10),
	 ('Антигуа и Барбуда','Antigua and Barbuda','AG',28),
	 ('Аргентина','Argentina','AR',32),
	 ('Армения','Armenia','AM',51),
	 ('Аруба','Aruba','AW',533),
	 ('Афганистан','Afghanistan','AF',4),
	 ('Багамы','Bahamas','BS',44),
	 ('Бангладеш','Bangladesh','BD',50),
	 ('Барбадос','Barbados','BB',52),
	 ('Бахрейн','Bahrain','BH',48);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Беларусь','Belarus','BY',112),
	 ('Белиз','Belize','BZ',84),
	 ('Бельгия','Belgium','BE',56),
	 ('Бенин','Benin','BJ',204),
	 ('Бермуды','Bermuda','BM',60),
	 ('Болгария','Bulgaria','BG',100),
	 ('Боливия, Многонациональное Государство','Bolivia, plurinational state of','BO',68),
	 ('Бонайре, Саба и Синт-Эстатиус','Bonaire, Sint Eustatius and Saba','BQ',535),
	 ('Босния и Герцеговина','Bosnia and Herzegovina','BA',70),
	 ('Ботсвана','Botswana','BW',72);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Бразилия','Brazil','BR',76),
	 ('Британская территория в Индийском океане','British Indian Ocean Territory','IO',86),
	 ('Бруней-Даруссалам','Brunei Darussalam','BN',96),
	 ('Буркина-Фасо','Burkina Faso','BF',854),
	 ('Бурунди','Burundi','BI',108),
	 ('Бутан','Bhutan','BT',64),
	 ('Вануату','Vanuatu','VU',548),
	 ('Венгрия','Hungary','HU',348),
	 ('Венесуэла Боливарианская Республика','Venezuela','VE',862),
	 ('Виргинские острова, Британские','Virgin Islands, British','VG',92);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Виргинские острова, США','Virgin Islands, U.S.','VI',850),
	 ('Вьетнам','Vietnam','VN',704),
	 ('Габон','Gabon','GA',266),
	 ('Гаити','Haiti','HT',332),
	 ('Гайана','Guyana','GY',328),
	 ('Гамбия','Gambia','GM',270),
	 ('Гана','Ghana','GH',288),
	 ('Гваделупа','Guadeloupe','GP',312),
	 ('Гватемала','Guatemala','GT',320),
	 ('Гвинея','Guinea','GN',324);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Гвинея-Бисау','Guinea-Bissau','GW',624),
	 ('Германия','Germany','DE',276),
	 ('Гернси','Guernsey','GG',831),
	 ('Гибралтар','Gibraltar','GI',292),
	 ('Гондурас','Honduras','HN',340),
	 ('Гонконг','Hong Kong','HK',344),
	 ('Гренада','Grenada','GD',308),
	 ('Гренландия','Greenland','GL',304),
	 ('Греция','Greece','GR',300),
	 ('Грузия','Georgia','GE',268);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Гуам','Guam','GU',316),
	 ('Дания','Denmark','DK',208),
	 ('Джерси','Jersey','JE',832),
	 ('Джибути','Djibouti','DJ',262),
	 ('Доминика','Dominica','DM',212),
	 ('Доминиканская Республика','Dominican Republic','DO',214),
	 ('Египет','Egypt','EG',818),
	 ('Замбия','Zambia','ZM',894),
	 ('Западная Сахара','Western Sahara','EH',732),
	 ('Зимбабве','Zimbabwe','ZW',716);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Израиль','Israel','IL',376),
	 ('Индия','India','IN',356),
	 ('Индонезия','Indonesia','ID',360),
	 ('Иордания','Jordan','JO',400),
	 ('Ирак','Iraq','IQ',368),
	 ('Иран, Исламская Республика','Iran, Islamic Republic of','IR',364),
	 ('Ирландия','Ireland','IE',372),
	 ('Исландия','Iceland','IS',352),
	 ('Испания','Spain','ES',724),
	 ('Италия','Italy','IT',380);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Йемен','Yemen','YE',887),
	 ('Кабо-Верде','Cape Verde','CV',132),
	 ('Казахстан','Kazakhstan','KZ',398),
	 ('Камбоджа','Cambodia','KH',116),
	 ('Камерун','Cameroon','CM',120),
	 ('Канада','Canada','CA',124),
	 ('Катар','Qatar','QA',634),
	 ('Кения','Kenya','KE',404),
	 ('Кипр','Cyprus','CY',196),
	 ('Киргизия','Kyrgyzstan','KG',417);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Кирибати','Kiribati','KI',296),
	 ('Китай','China','CN',156),
	 ('Кокосовые (Килинг) острова','Cocos (Keeling) Islands','CC',166),
	 ('Колумбия','Colombia','CO',170),
	 ('Коморы','Comoros','KM',174),
	 ('Конго','Congo','CG',178),
	 ('Конго, Демократическая Республика','Congo, Democratic Republic of the','CD',180),
	 ('Корея, Народно-Демократическая Республика','Korea, Democratic People''s republic of','KP',408),
	 ('Корея, Республика','Korea, Republic of','KR',410),
	 ('Коста-Рика','Costa Rica','CR',188);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Кот д''Ивуар','Cote d''Ivoire','CI',384),
	 ('Куба','Cuba','CU',192),
	 ('Кувейт','Kuwait','KW',414),
	 ('Кюрасао','Curaçao','CW',531),
	 ('Лаос','Lao People''s Democratic Republic','LA',418),
	 ('Латвия','Latvia','LV',428),
	 ('Лесото','Lesotho','LS',426),
	 ('Ливан','Lebanon','LB',422),
	 ('Ливийская Арабская Джамахирия','Libyan Arab Jamahiriya','LY',434),
	 ('Либерия','Liberia','LR',430);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Лихтенштейн','Liechtenstein','LI',438),
	 ('Литва','Lithuania','LT',440),
	 ('Люксембург','Luxembourg','LU',442),
	 ('Маврикий','Mauritius','MU',480),
	 ('Мавритания','Mauritania','MR',478),
	 ('Мадагаскар','Madagascar','MG',450),
	 ('Майотта','Mayotte','YT',175),
	 ('Макао','Macao','MO',446),
	 ('Малави','Malawi','MW',454),
	 ('Малайзия','Malaysia','MY',458);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Мали','Mali','ML',466),
	 ('Малые Тихоокеанские отдаленные острова Соединенных Штатов','United States Minor Outlying Islands','UM',581),
	 ('Мальдивы','Maldives','MV',462),
	 ('Мальта','Malta','MT',470),
	 ('Марокко','Morocco','MA',504),
	 ('Мартиника','Martinique','MQ',474),
	 ('Маршалловы острова','Marshall Islands','MH',584),
	 ('Мексика','Mexico','MX',484),
	 ('Микронезия, Федеративные Штаты','Micronesia, Federated States of','FM',583),
	 ('Мозамбик','Mozambique','MZ',508);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Молдова, Республика','Moldova','MD',498),
	 ('Монако','Monaco','MC',492),
	 ('Монголия','Mongolia','MN',496),
	 ('Монтсеррат','Montserrat','MS',500),
	 ('Мьянма','Myanmar','MM',104),
	 ('Намибия','Namibia','NA',516),
	 ('Науру','Nauru','NR',520),
	 ('Непал','Nepal','NP',524),
	 ('Нигер','Niger','NE',562),
	 ('Нигерия','Nigeria','NG',566);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Нидерланды','Netherlands','NL',528),
	 ('Никарагуа','Nicaragua','NI',558),
	 ('Ниуэ','Niue','NU',570),
	 ('Новая Зеландия','New Zealand','NZ',554),
	 ('Новая Каледония','New Caledonia','NC',540),
	 ('Норвегия','Norway','NO',578),
	 ('Объединенные Арабские Эмираты','United Arab Emirates','AE',784),
	 ('Оман','Oman','OM',512),
	 ('Остров Буве','Bouvet Island','BV',74),
	 ('Остров Мэн','Isle of Man','IM',833);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Остров Норфолк','Norfolk Island','NF',574),
	 ('Остров Рождества','Christmas Island','CX',162),
	 ('Остров Херд и острова Макдональд','Heard Island and McDonald Islands','HM',334),
	 ('Острова Кайман','Cayman Islands','KY',136),
	 ('Острова Кука','Cook Islands','CK',184),
	 ('Острова Теркс и Кайкос','Turks and Caicos Islands','TC',796),
	 ('Пакистан','Pakistan','PK',586),
	 ('Палау','Palau','PW',585),
	 ('Палестинская территория, оккупированная','Palestinian Territory, Occupied','PS',275),
	 ('Панама','Panama','PA',591);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Папский Престол (Государство — город Ватикан)','Holy See (Vatican City State)','VA',336),
	 ('Папуа-Новая Гвинея','Papua New Guinea','PG',598),
	 ('Парагвай','Paraguay','PY',600),
	 ('Перу','Peru','PE',604),
	 ('Питкерн','Pitcairn','PN',612),
	 ('Польша','Poland','PL',616),
	 ('Португалия','Portugal','PT',620),
	 ('Пуэрто-Рико','Puerto Rico','PR',630),
	 ('Республика Македония','Macedonia, The Former Yugoslav Republic Of','MK',807),
	 ('Реюньон','Reunion','RE',638);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Россия','Russian Federation','RU',643),
	 ('Руанда','Rwanda','RW',646),
	 ('Румыния','Romania','RO',642),
	 ('Самоа','Samoa','WS',882),
	 ('Сан-Марино','San Marino','SM',674),
	 ('Сан-Томе и Принсипи','Sao Tome and Principe','ST',678),
	 ('Саудовская Аравия','Saudi Arabia','SA',682),
	 ('Свазиленд','Swaziland','SZ',748),
	 ('Святая Елена, Остров вознесения, Тристан-да-Кунья','Saint Helena, Ascension And Tristan Da Cunha','SH',654),
	 ('Северные Марианские острова','Northern Mariana Islands','MP',580);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Сен-Бартельми','Saint Barthélemy','BL',652),
	 ('Сен-Мартен','Saint Martin (French Part)','MF',663),
	 ('Сенегал','Senegal','SN',686),
	 ('Сент-Винсент и Гренадины','Saint Vincent and the Grenadines','VC',670),
	 ('Сент-Люсия','Saint Lucia','LC',662),
	 ('Сент-Китс и Невис','Saint Kitts and Nevis','KN',659),
	 ('Сент-Пьер и Микелон','Saint Pierre and Miquelon','PM',666),
	 ('Сербия','Serbia','RS',688),
	 ('Сейшелы','Seychelles','SC',690),
	 ('Сингапур','Singapore','SG',702);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Синт-Мартен','Sint Maarten','SX',534),
	 ('Сирийская Арабская Республика','Syrian Arab Republic','SY',760),
	 ('Словакия','Slovakia','SK',703),
	 ('Словения','Slovenia','SI',705),
	 ('Соединенное Королевство','United Kingdom','GB',826),
	 ('Соединенные Штаты','United States','US',840),
	 ('Соломоновы острова','Solomon Islands','SB',90),
	 ('Сомали','Somalia','SO',706),
	 ('Судан','Sudan','SD',729),
	 ('Суринам','Suriname','SR',740);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Сьерра-Леоне','Sierra Leone','SL',694),
	 ('Таджикистан','Tajikistan','TJ',762),
	 ('Таиланд','Thailand','TH',764),
	 ('Тайвань (Китай)','Taiwan, Province of China','TW',158),
	 ('Танзания, Объединенная Республика','Tanzania, United Republic Of','TZ',834),
	 ('Тимор-Лесте','Timor-Leste','TL',626),
	 ('Того','Togo','TG',768),
	 ('Токелау','Tokelau','TK',772),
	 ('Тонга','Tonga','TO',776),
	 ('Тринидад и Тобаго','Trinidad and Tobago','TT',780);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Тувалу','Tuvalu','TV',798),
	 ('Тунис','Tunisia','TN',788),
	 ('Туркмения','Turkmenistan','TM',795),
	 ('Турция','Turkey','TR',792),
	 ('Уганда','Uganda','UG',800),
	 ('Узбекистан','Uzbekistan','UZ',860),
	 ('Украина','Ukraine','UA',804),
	 ('Уоллис и Футуна','Wallis and Futuna','WF',876),
	 ('Уругвай','Uruguay','UY',858),
	 ('Фарерские острова','Faroe Islands','FO',234);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Фиджи','Fiji','FJ',242),
	 ('Филиппины','Philippines','PH',608),
	 ('Финляндия','Finland','FI',246),
	 ('Фолклендские острова (Мальвинские)','Falkland Islands (Malvinas)','FK',238),
	 ('Франция','France','FR',250),
	 ('Французская Гвиана','French Guiana','GF',254),
	 ('Французская Полинезия','French Polynesia','PF',258),
	 ('Французские Южные территории','French Southern Territories','TF',260),
	 ('Хорватия','Croatia','HR',191),
	 ('Центрально-Африканская Республика','Central African Republic','CF',140);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Чад','Chad','TD',148),
	 ('Черногория','Montenegro','ME',499),
	 ('Чешская Республика','Czech Republic','CZ',203),
	 ('Чили','Chile','CL',152),
	 ('Швейцария','Switzerland','CH',756),
	 ('Швеция','Sweden','SE',752),
	 ('Шпицберген и Ян Майен','Svalbard and Jan Mayen','SJ',744),
	 ('Шри-Ланка','Sri Lanka','LK',144),
	 ('Эквадор','Ecuador','EC',218),
	 ('Экваториальная Гвинея','Equatorial Guinea','GQ',226);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Эландские острова','Åland Islands','AX',248),
	 ('Эль-Сальвадор','El Salvador','SV',222),
	 ('Эритрея','Eritrea','ER',232),
	 ('Эстония','Estonia','EE',233),
	 ('Эфиопия','Ethiopia','ET',231),
	 ('Южная Африка','South Africa','ZA',710),
	 ('Южная Джорджия и Южные Сандвичевы острова','South Georgia and the South Sandwich Islands','GS',239),
	 ('Южная Осетия','South Ossetia','OS',896),
	 ('Южный Судан','South Sudan','SS',728),
	 ('Ямайка','Jamaica','JM',388);
INSERT INTO public.countries (name_ru,name_eng,literal_code,numeric_code) VALUES
	 ('Япония','Japan','JP',392);
INSERT INTO public.direction_types ("name") VALUES
	 ('Информационная безопасность'),
	 ('Биг Дата'),
	 ('ИТ'),
	 ('Дизайн'),
	 ('Аналитика');
INSERT INTO public.events (description,day_number,start_time) VALUES
	 ('Перспективные направления IT',2,'0001-01-01 10:45:00'),
	 ('Современные технологии',2,'0001-01-01 12:30:00'),
	 ('Что такое IOT?',1,'0001-01-01 09:00:00'),
	 ('Для чего это нужно?',2,'0001-01-01 10:45:00'),
	 ('Новые продукты и версии',2,'0001-01-01 12:30:00'),
	 ('Как составить план?',1,'0001-01-01 09:00:00'),
	 ('Что такое план?',2,'0001-01-01 10:45:00'),
	 ('Must Have 21 века',2,'0001-01-01 12:30:00'),
	 ('Управление знаниями',1,'0001-01-01 09:00:00'),
	 ('Коммуникативные неудачи',1,'0001-01-01 10:45:00');
INSERT INTO public.events (description,day_number,start_time) VALUES
	 ('Дизайн-мышление',2,'0001-01-01 12:30:00'),
	 ('Технические собеседования',1,'0001-01-01 09:00:00'),
	 ('Исследование рынка',2,'0001-01-01 10:45:00'),
	 ('Подготовка специалистов',3,'0001-01-01 12:30:00'),
	 ('Секреты успеха',1,'0001-01-01 09:00:00'),
	 ('Способы поиска специалистов',1,'0001-01-01 10:45:00'),
	 ('Что нужно пользователям?',1,'0001-01-01 12:30:00'),
	 ('Осознанность личных целей',1,'0001-01-01 09:00:00'),
	 ('Soft skills',1,'0001-01-01 10:45:00'),
	 ('Развитие проактивности',2,'0001-01-01 12:30:00');
INSERT INTO public.events (description,day_number,start_time) VALUES
	 ('Введение в IT-субкультуру',1,'0001-01-01 09:00:00'),
	 ('Основы ООП',1,'0001-01-01 10:45:00'),
	 ('Что нужно знать начинающему спецалисту',1,'0001-01-01 16:00:00'),
	 ('Идельный результат',1,'0001-01-01 09:00:00'),
	 ('Тайны и секреты',2,'0001-01-01 10:45:00'),
	 ('Какрой язык программирования выбрать?',2,'0001-01-01 12:30:00'),
	 ('Войти в ТОП',1,'0001-01-01 09:00:00'),
	 ('Секреты продвижения',1,'0001-01-01 10:45:00'),
	 ('Руководство проектами',2,'0001-01-01 12:30:00'),
	 ('ТОП 50 ',1,'0001-01-01 09:00:00');
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.events_jurors () VALUES
	 (),
	 (),
	 ();
INSERT INTO public.genders ("name") VALUES
	 ('мужчина'),
	 ('женщина');
INSERT INTO public.jurors () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.moderators () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.moderators () VALUES
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 (),
	 ();
INSERT INTO public.moderators () VALUES
	 ();
INSERT INTO public.roles ("name") VALUES
	 ('участник'),
	 ('организатор'),
	 ('модератор'),
	 ('жюри');
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Корнилов Владимир Степанович','4sqplurb5eki@gmail.com','1991-02-08 00:00:00','7(821)277-59-90','nOEBrK','foto12.jpg',1),
	 ('Трофимов Любомир Русланович','m73dobuzn6jc@gmail.com','1980-02-11 00:00:00','7(821)611-43-32','TImO7k','foto13.jpg',1),
	 ('Симонов Остап Федотович','9mtkjdsrhp2c@yahoo.com','1989-01-14 00:00:00','7(821)779-78-75','PtwSEA','foto14.jpg',1),
	 ('Захаров Арнольд Германнович','wxey0gmcjuz2@mail.com','1994-07-30 00:00:00','7(821)819-98-39','EzwyiP','foto15.jpg',1),
	 ('Фокин Клемент Игнатьевич','lqih53fw9ryx@tutanota.com','1973-01-15 00:00:00','7(821)177-06-74','pEVpH3','foto16.jpg',1),
	 ('Захаров Аверкий Альбертович','p473g2jlcmhi@outlook.com','1981-06-24 00:00:00','7(821)856-28-93','eEJ83V','foto17.jpg',1),
	 ('Егоров Афанасий Тарасович','t1dg96ikvorc@tutanota.com','1977-06-26 00:00:00','7(821)623-59-80','0Utzck','foto18.jpg',1),
	 ('Ермаков Клемент Проклович','ah91upwo7xfl@mail.com','1972-12-04 00:00:00','7(821)007-84-60','HLAFQB','foto19.jpg',1),
	 ('Лазарев Марк Юлианович','fskhuw2oxgev@outlook.com','1996-05-11 00:00:00','7(821)376-94-02','nrBfHG','foto20.jpg',1),
	 ('Петров Геннадий Даниилович','6opkrq9n87d1@outlook.com','1989-08-06 00:00:00','7(821)685-48-91','xM5QB5','foto21.jpg',1);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Субботин Мартин Пантелеймонович','epflsy9iobdx@tutanota.com','1989-04-26 00:00:00','7(821)149-13-09','v5MxkG','foto22.jpg',1),
	 ('Рожков Демьян Эдуардович','zy8tom2bxnuk@mail.com','1995-11-09 00:00:00','7(821)162-52-21','8MkKg6','foto23.jpg',1),
	 ('Емельянов Анатолий Авксентьевич','kd64ino5fcx3@outlook.com','1982-10-17 00:00:00','7(821)976-48-88','COZkSO','foto24.jpg',1),
	 ('Петухов Алан Пётрович','i4ex5whc7dqk@gmail.com','1987-01-29 00:00:00','7(821)749-53-09','GYlXDR','foto25.jpg',1),
	 ('Бобров Марк Юрьевич','qsnyrwodje0k@outlook.com','1993-12-08 00:00:00','7(821)496-70-50','10PHSE','foto26.jpg',1),
	 ('Александров Варлаам Робертович','tacixb04vh5g@gmail.com','1999-05-18 00:00:00','7(821)137-45-80','uNRgsg','foto27.jpg',1),
	 ('Максимов Егор Дамирович','96o7iwszty5n@tutanota.com','1975-11-30 00:00:00','7(821)579-45-88','9YNtvb','foto28.jpg',1),
	 ('Комиссаров Антон Протасьевич','yn6pfe4kasbo@outlook.com','1996-11-15 00:00:00','7(821)277-58-70','4rSPmK','foto29.jpg',1),
	 ('Мамонтов Прохор Созонович','vny26gsmxu9k@tutanota.com','1975-12-30 00:00:00','7(821)760-71-19','STSVII','foto30.jpg',1),
	 ('Баранов Венедикт Ефимович','mwlny4zqtc65@outlook.com','1988-07-15 00:00:00','7(821)478-05-95','DsEhqN','foto31.jpg',1);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Скворцов Михаил Артёмович','3swfq0n756y1@mail.com','1989-01-05 00:00:00','7(329)246-20-13','JyP2M2ji63','foto1.jpg',2),
	 ('Романова Анастасия Тимофеевна','wukm6dacf7v0@gmail.com','1980-09-01 00:00:00','7(226)494-15-47','8fb3RJT8c6','foto2.jpg',2),
	 ('Белкин Дмитрий Александрович','5ku2w7nqzvot@gmail.com','1981-03-02 00:00:00','7(725)164-24-56','2T2xCYef86','foto3.jpg',2),
	 ('Лаврова Анастасия Маратовна','8s54jayek2mt@outlook.com','1981-09-12 00:00:00','7(388)191-50-31','nG7xGVi892','foto4.jpg',2),
	 ('Громова Виктория Матвеевна','dlm7wocnzhtp@mail.com','1983-07-14 00:00:00','7(581)960-76-73','Ka74TC2r7m','foto5.jpg',2),
	 ('Карпов Алексей Артёмович','ekibvrcm71a6@gmail.com','1980-08-06 00:00:00','7(959)240-88-47','fk9BHN2g96','foto6.jpg',2),
	 ('Прохоров Максим Серафимович','70rkvgtfjswm@gmail.com','1995-11-10 00:00:00','7(466)705-98-66','9nM7A9Mtv5','foto7.jpg',2),
	 ('Мешков Даниил Николаевич','vy3ajxkge8p7@mail.com','1984-11-20 00:00:00','7(640)704-75-62','d6UAu83Sd8','foto8.jpg',2),
	 ('Рябова Алиса Викторовна','tkgduj6na1hm@gmail.com','1989-01-14 00:00:00','7(500)841-51-43','JS4K8pr54u','foto9.jpg',2),
	 ('Соловьев Демид Артёмович','uw846cn27x9k@outlook.com','1981-12-21 00:00:00','7(053)696-95-19','42xF46LVkh','foto10.jpg',2);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Покровский Роман Дмитриевич','i8brhz2gyx4j@gmail.com','1974-01-22 00:00:00','7(416)870-22-00','4VUmGj4t36','foto9.jpg',3),
	 ('Чернышев Ярослав Андреевич','dic8qah9zbot@mail.com','1957-06-12 00:00:00','7(278)138-47-92','b9zAs99XD3','foto10.jpg',3),
	 ('Суворова Ева Алексеевна','o3gmly907wcn@mail.com','1960-05-29 00:00:00','7(093)787-84-57','n6cx69AM4T','foto8.jpg',3),
	 ('Лосева Аделина Георгиевна','qz901omryb7j@mail.com','1996-08-11 00:00:00','7(699)704-90-18','P8c83u5fUR','foto11.jpg',3),
	 ('Покровский Марк Максимович','m93nsaih4kl8@yahoo.com','1968-09-23 00:00:00','7(312)920-22-96','f7S5zxH58B','foto12.jpg',3),
	 ('Акимова София Александровна','qgb9ea8wnl50@mail.com','1989-01-20 00:00:00','7(714)693-32-92','c2vGi532VN','foto13.jpg',3),
	 ('Майоров Александр Михайлович','rzsj6wqd42vt@yahoo.com','1998-05-01 00:00:00','7(605)246-65-83','8jZ5LL2a2n','foto14.jpg',3),
	 ('Прохорова Анна Фёдоровна','wg9h3ixavl25@tutanota.com','1982-05-24 00:00:00','7(037)333-08-17','D44jjR45gH','foto16.jpg',3),
	 ('Соловьев Иван Дмитриевич','2nib6c5vl18k@outlook.com','1969-03-28 00:00:00','7(594)615-77-80','2c73vxTLP9','foto17.jpg',3),
	 ('Лебедева Виктория Марковна','wbs3znh5uxfr@tutanota.com','1980-10-30 00:00:00','7(596)301-43-97','69S6fMzeM2','foto18.jpg',3);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Шишкина Светлана Александровна','yl9hxt5dzajv@tutanota.com','1998-02-08 00:00:00','7(181)588-68-39','j7TMm92s9X','foto19.jpg',3),
	 ('Юдина Татьяна Максимовна','4rqfa385p9gz@mail.com','1978-01-27 00:00:00','7(442)333-89-12','XU5b8N42th','foto20.jpg',3),
	 ('Рябинин Григорий Матвеевич','ox7k5w6l04mi@gmail.com','1953-05-31 00:00:00','7(377)251-56-96','6R82k4nFnX','foto21.jpg',3),
	 ('Тарасова Валерия Егоровна','a8071jvd2m6z@tutanota.com','1975-12-24 00:00:00','7(575)142-09-75','eC445cE8Yd','foto22.jpg',3),
	 ('Алексеев Михаил Глебович','qxel0og2ps4t@gmail.com','1976-05-12 00:00:00','7(979)385-40-57','8T69Vef8Er','foto23.jpg',3),
	 ('Иванова Виктория Павловна','ixut6e0cnd84@gmail.com','1973-05-09 00:00:00','7(901)002-16-80','34nYAv56Cs','foto24.jpg',3),
	 ('Богданова Олеся Евгеньевна','es06joah3pfu@gmail.com','1962-08-26 00:00:00','7(272)350-20-30','ru6x7PT2V4','foto25.jpg',3),
	 ('Иванов Фёдор Тимофеевич','0kmd26jfi859@mail.com','1988-11-23 00:00:00','7(812)026-33-34','a7pXZ78a2J','foto26.jpg',3),
	 ('Кузнецов Семён Владиславович','mn7bawsorg51@outlook.com','1962-05-05 00:00:00','7(550)677-95-09','8uTv4L8Cg4','foto27.jpg',3),
	 ('Шульгина Елизавета Денисовна','1os2bmtpg6nv@mail.com','1989-01-13 00:00:00','7(596)221-45-84','6VM3r9jmS5','foto28.jpg',3);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Петрова Василиса Георгиевна','vbpjslo28w6d@mail.com','1987-04-25 00:00:00','7(588)448-48-41','c6m4L2ZD9j','foto29.jpg',3),
	 ('Одинцов Дмитрий Лаврентьевич','oconnell.steve@feest.com','1978-03-02 00:00:00','7(186)808-50-25','ugWkzE','foto11.jpg',4),
	 ('Белова Инга Прокловна','olson.shanny@gmail.com','1972-09-15 00:00:00','7(215)064-59-70','TsCX7X','foto12.jpg',4),
	 ('Соловьёва Аюна Станиславовна','whirthe@beer.info','1950-02-21 00:00:00','7(810)322-94-05','R2buBG','foto13.jpg',4),
	 ('Зайцев Иван Артемович','rerdman@gmail.com','1950-07-20 00:00:00','7(963)659-08-16','6Kuk9B','foto14.jpg',4),
	 ('Некрасова Лаура Богдановна','pkutch@hotmail.com','1950-08-19 00:00:00','7(138)268-54-96','XQZbTX','foto15.jpg',4),
	 ('Брагин Осип Владиславович','trace.lindgren@beahan.com','1963-06-03 00:00:00','7(276)229-95-45','AA6JS6','foto16.jpg',4),
	 ('Игнатьев Мирослав Тарасович','jadon85@gmail.com','1973-07-03 00:00:00','7(346)523-76-14','j7WWL5','foto17.jpg',4),
	 ('Матвеева Вера Митрофановна','mathilde77@yahoo.com','1952-11-09 00:00:00','7(742)194-06-10','2QCbSj','foto18.jpg',4),
	 ('Пестова Ева Альбертовна','graham.robb@boyer.com','1980-09-24 00:00:00','7(089)418-02-33','kFwax6','foto19.jpg',4);
INSERT INTO public.users (full_name,mail,date_of_birth,phone_number,"password",image,"role") VALUES
	 ('Фомичёв Варлаам Дмитрьевич','cleveland.hamill@gmail.com','1994-09-26 00:00:00','7(097)858-38-14','SqJHTL','foto20.jpg',4);
